# 0x Default colors
[colors.primary]
background = "{{  background  }}"
foreground = "{{  foreground  }}"

# 0x Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "{{  cursor  }}"
cursor = "{{  selection_background  }}"

# 0x Normal colors
[colors.normal]
black   = "{{  color0  }}"
red     = "{{  color1  }}"
green   = "{{  color2  }}"
yellow  = "{{  color3  }}"
blue    = "{{  color4  }}"
magenta = "{{  color5  }}"
cyan    = "{{  color6  }}"
white   = "{{  color7  }}"

# 0x Bright colors
[colors.bright]
black   = "{{  color8  }}"
red     = "{{  color9  }}"
green   = "{{  color10  }}"
yellow  = "{{  color11  }}"
blue    = "{{  color12  }}"
magenta = "{{  color13  }}"
cyan    = "{{  color14  }}"
white   = "{{  foreground  }}"
